### ISSUE TITLE
Documentation no longer deployed

### ISSUE THREAD

**Issue by franckgaga** [JuliaControl/ModelPredictiveControl.jl#26]
@baggepinnen 

It seems that dev documentation is no longer automatically built and deployed when I commit on `main`. It was working perfectly before transferring to JuliaControl. Do you have any idea why ? It may be related to secrets key (in documentation.yml):
```yml
env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
```
I'm no longer able to access the secrets in repo settings since I'm not an admin.

Also, I just registered a new version. I'm waiting to see if the stable doc will be built and deployed.

edit: yep, it is also broken with the stable doc
